//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlUniversitario.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatriculaDeCurso
    {
        public long EstudianteID { get; set; }
        public int CursoID { get; set; }
        public System.DateTime FechaDeMatricula { get; set; }
        public string Cuatrimestre { get; set; }
        public decimal PrecioMatricula { get; set; }
    
        public virtual Estudiante Estudiante { get; set; }
        public virtual Curso Curso { get; set; }
    }
}
